[project]
name = 'nft_demo'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.commission-trait]
path = 'contracts/commission-trait.clar'

[contracts.nft]
path = 'contracts/nft.clar'
depends_on = ["ST2PABAF9FTAJYNFZH93XENAJ8FVY99RRM4DF2YCW.nft-trait", ".commission-trait"]

[contracts.tipping]
path = 'contracts/tipping.clar'


[contracts.ft]
path = 'contracts/ft.clar'

[repl]
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false